on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotfiles
        run: setup.sh
