on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup.sh
        run: bash setup.sh
        shell: zsh {0}
        env:
          SHELL: /usr/bin/zsh
      - name: Source .zshrc
        run: source zsh/.zshrc
        shell: zsh {0}
        env:
          SHELL: /usr/bin/zsh
